#!/bin/sh -e

BACKUPS=/backups
KEY_DIR=/mnt/keydir

DESTINATION=$1
if [ -z "$DESTINATION" ]
then
  echo "$0 destination container [container...]"
  echo "(If set, docker-backup output will be POSTed to \$PUSHGATEWAY)"
  exit 1
fi
shift

if [ -z "$USERNAME" -o -z "$PRIVATE_KEY" ]
then
  echo "Please set USERNAME and PRIVATE_KEY environment variables"
  exit 1
fi

[ -d "$BACKUPS" ] || mkdir "$BACKUPS"

push_metrics() {
  [ -z "$PUSHGATEWAY" ] && return
  curl --data-binary @- "$PUSHGATEWAY"
}

backup() {
  echo "[=] $1"
  while true
  do
    echo "$1: Backup"
    /docker-backup/docker-backup $OPTS -addr /docker.sock store "$BACKUPS/$1.tar" "$1" | push_metrics
    gzip "$BACKUPS/$1.tar"

    echo "$1: Upload"
    scp -C -q -i "$KEY_DIR/$PRIVATE_KEY" "BACKUPS/$1.tar.gz" $USERNAME@$DESTINATION
    rm "$BACKUPS/$1.tar.gz"

    date +"last_run{container=\"$1\"} %s" | push_metrics
  done
}

for c in $@
do
  backup $c &
done

wait
